# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import morango.utils.uuids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kolibriauth', '0011_facilitydataset_show_download_button_in_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('_morango_dirty_bit', models.BooleanField(default=True, editable=False)),
                ('_morango_source_id', models.CharField(editable=False, max_length=96)),
                ('_morango_partition', models.CharField(editable=False, max_length=128)),
                ('data', jsonfield.fields.JSONField(blank=True, default={})),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.FacilityDataset')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolibriauth.Facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
