# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:29
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_pratham_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='name',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
