# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:50
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_pratham_plugin', '0002_datastore_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastore',
            old_name='name',
            new_name='table_name',
        ),
        migrations.AddField(
            model_name='datastore',
            name='filter',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
