# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_pratham_plugin', '0003_auto_20180423_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='filter',
        ),
        migrations.AddField(
            model_name='datastore',
            name='village_name',
            field=models.CharField(default=b'enter village name', max_length=100),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='table_name',
            field=models.CharField(default=b'enter name', max_length=100),
        ),
    ]
