# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_pratham_plugin', '0004_auto_20180424_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastore',
            name='village_name',
        ),
        migrations.AddField(
            model_name='datastore',
            name='filter_name',
            field=models.CharField(default=b'enter filter name', max_length=100),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='table_name',
            field=models.CharField(default=b'enter table name', max_length=100),
        ),
    ]
