# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolibri_pratham_plugin', '0005_auto_20180424_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
